routes/web.php
<?php

use App\Http\Controllers\PriceController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', ProductController::class);
Route::resource('products', ProductController::class);
Route::resource('prices', PriceController::class);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Price.php
<?php

namespace App\Models;

use  Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Class Price
 *
 * @property integer id
 * @property string name
 * @property float value
 * @property int product_id
 */

class Price extends Model
{
    use HasFactory;

    public const TABLE = 'prices';

    public const COLUMN_ID = 'id';
    public const COLUMN_NAME = 'name';
    public const COLUMN_VALUE = 'value';
    public const COLUMN_PRODUCT_ID = 'product_id';

    public const RELATION_PRODUCT = 'product';

    public $timestamps = true;
    protected $table = self::TABLE;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        self::COLUMN_NAME,
        self::COLUMN_VALUE,
        self::COLUMN_PRODUCT_ID,
    ];

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class, self::COLUMN_PRODUCT_ID);
    }

}

app/Http/Controllers/PriceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePriceRequest;
use App\Http\Requests\UpdatePriceRequest;
use App\Models\Price;
use App\Models\Product;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class PriceController extends Controller
{
    public function index(): View
    {
        $prices = Price::query()
            ->with([
                Price::RELATION_PRODUCT
            ])
            ->paginate(25);

        return view('prices.index', compact('prices'));
    }

    public function create(): View
    {
        $products = Product::query()->get();
        return view('prices.create', compact('products'));
    }

    public function store(CreatePriceRequest $request): RedirectResponse
    {
        $price = new Price([
            Price::COLUMN_NAME => $request->getNameInput(),
            Price::COLUMN_PRODUCT_ID => $request->getProductIdInput(),
            Price::COLUMN_VALUE => $request->getValueInput(),
        ]);
        $price->product()->associate($request->getProductIdInput());

        $price->save();

        $price->load(
            Price::RELATION_PRODUCT,
        );

        return redirect()->route('prices.index');
    }

    public function show(Price $price): View
    {
        return view('prices.show', compact('price'));
    }

    public function edit(Price $price): View
    {
        $products = Product::query()->get();
        return view('prices.edit', compact('price', 'products'));
    }

    public function update(UpdatePriceRequest $request, Price $price): RedirectResponse
    {
        $price->fill([
            Price::COLUMN_NAME => $request->getNameInput(),
            Price::COLUMN_PRODUCT_ID => $request->getProductIdInput(),
            Price::COLUMN_VALUE => $request->getValueInput(),
        ]);
        $price->product()->associate($request->getProductIdInput());

        $price->save();

        $price->load(
            Price::RELATION_PRODUCT,
        );

        return redirect()->route('prices.index');
    }

    public function destroy(Price $price): RedirectResponse
    {
        $price->delete();
        return redirect()->route('prices.index');
    }
}

resources/views/prices/create.blade.php
@extends('App')
@section('title', 'Dodaj cenę')

@section('content')
    <main class="content col-md-9 ms-sm-auto col-lg-10 px-md-4">
        @auth
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2">@yield('title')</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('prices.index') }}"><button type="button" class="btn btn-sm btn-outline-secondary">Powrót do listy</button></a>
                </div>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    <form action="{{ route('prices.store') }}" method="POST" >
        @csrf
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="value">Nazwa</label>
                    <input type="text" class="form-control" id="name" name="name">
                </div>
                <div class="form-group">
                    <label for="value">Wartość</label>
                    <input type="text" class="form-control" id="value" name="value">
                </div>
                <div class="form-group">
                    <label for="product_id">Produkt</label>
                    <select class="form-control" id="product_id" name="product_id">
                        @foreach($products as $product)
                            <option value="{{ $product->id }}">{{ $product->name }}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Zapisz</button>
            </div>
        </div>

    </form>

        @else
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Restricted Area!
            </div>
        @endauth
    </main>
    </main>

@endsection

resources/views/prices/edit.blade.php
@extends('App')
@section('title', 'Edytuj cenę')

@section('content')
    <main class="content col-md-9 ms-sm-auto col-lg-10 px-md-4">
        @auth
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2">@yield('title')</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('prices.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-secondary">Powrót do listy</button>
                    </a>
                </div>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('prices.update', $price->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="name">Nazwa ceny</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ $price->name }}"/>
                    </div>
                    <div class="form-group">
                        <label for="value">Wartość</label>
                        <input type="text" class="form-control" id="value" name="value" value="{{ $price->value }}"/>
                    </div>
                    <div class="form-group">
                        <label for="product_id">Produkt</label>
                        <select class="form-control" id="product_id" name="product_id">
                            @foreach($products as $product)
                                <option
                                    value="{{ $product->id }}"
                                    @if ($product->id == $price->product->id )
                                    selected
                                    @endif>{{ $product->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Zapisz</button>
                </div>
            </div>

        </form>

        @else
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Restricted Area!
            </div>
        @endauth
    </main>
    </main>

@endsection

resources/views/prices/index.blade.php
@extends('App')
@section('title', 'Lista cen')

@section('content')
    <main class="content col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2">@yield('title')</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    @auth
                        <a href="{{ URL::to('prices/create') }}">
                            <button type="button" class="btn btn-success">Dodaj</button>
                        </a>
                    @endauth
                </div>
            </div>
        </div>
        {{ $prices->links() }}
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Cena</th>
                    <th>Wartość</th>
                    <th>Produkt</th>
                    @auth
                        <th>Akcja</th>@endauth
                </tr>
                </thead>

                <tbody>
                @foreach($prices as $price)
                    <tr>
                        <td>
                            <a href="{{ URL::to('prices/'.$price->id) }}">{{ $price->name }}</a>
                        </td>
                        <td>{{ $price->value }} zł</td>
                        <td><a href="{{ URL::to('products/'.$price->product->id) }}">{{ $price->product->name }}</a>
                        </td>
                        @auth
                            <td>
                                <a href="{{ route('prices.edit', ['price' => $price->id]) }}">
                                    <button type="button" class="btn btn-sm btn-success">Edytuj
                                    </button>
                                </a>
                                <form action="{{ route('prices.destroy', ['price' => $price->id]) }}" method="POST"
                                      style="display: inline;">
                                    @csrf
                                    <input type="hidden" name="_method" value="DELETE"/>
                                    <input type="submit" value="Usuń" name="Usuń" class="btn btn-sm btn-danger"
                                           accesskey="x"/>
                                </form>
                            </td>
                        @endauth
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $prices->links() }}
        </div>
    </main>
@endsection

resources/views/prices/show.blade.php
@extends('App')
@section('title', 'Zobacz ceny')

@section('content')
    <main class="content col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2">@yield('title')</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('prices.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-secondary">Powrót do listy</button>
                    </a>&nbsp;
                    @auth
                        <a href="{{ route('prices.edit', ['price' => $price->id]) }}">
                            <button type="button" class="btn btn-sm btn-success">Edytuj
                            </button>
                        </a>
                    @endauth                </div>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <h1 class="mb-12">Produkt: {{ $price->product->name }}</h1>

            <form action="{{ route('prices.destroy', ['price' => $price->id]) }}" method="POST"
                  style="display: inline;">
                @csrf
                <input type="hidden" name="_method" value="DELETE"/>
                <button type="submit" class="btn btn-primary">
                    {{ $price->name }}: <span class="badge badge-light">{{ $price->value }}</span> <i
                        class="fas fa-minus-circle"></i>
                </button>
            </form>

    </main>
@endsection