routes/web.php
<?php

use App\Http\Controllers\PriceController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', ProductController::class);
Route::resource('products', ProductController::class);
Route::resource('prices', PriceController::class);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use  Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Class Product
 *
 * @property integer id
 * @property string name
 * @property string description
 * @property string image_url
 */

class Product extends Model
{
    use HasFactory;

    public const TABLE = 'products';

    public const COLUMN_ID = 'id';
    public const COLUMN_NAME = 'name';
    public const COLUMN_DESCRIPTION = 'description';
    public const COLUMN_IMAGE = 'image';

    public $timestamps = true;
    protected $table = self::TABLE;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        self::COLUMN_NAME,
        self::COLUMN_DESCRIPTION,
        self::COLUMN_IMAGE,
    ];

    public function price(): HasMany
    {
        return $this->hasMany(Price::class, Price::COLUMN_PRODUCT_ID);
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductListRequest;
use App\Models\Product;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\View\View;
use App\Traits\UploadTrait;
use Illuminate\Database\Eloquent\Builder;


class ProductController extends Controller
{
    use UploadTrait;

    public function index(ProductListRequest $request): View
    {
        $products = Product::query()
            ->when(!empty($request->getSearchInput()), function (Builder $query) use ($request) {
                $query->where(Product::COLUMN_NAME, 'LIKE', '%'.$request->getSearchInput().'%');
            })
            ->when(
                $request->getOrderByInput(),
                function (Builder $query) use ($request) {
                    return $query->orderBy($request->getOrderByInput(), $request->getDirectionInput());
                }
            )
            ->paginate(25);
        return view('products.index', compact('products'));
    }

    public function create(): View
    {
            return view('products.create');
    }

    public function store(Request $request): RedirectResponse
    {

        $request->validate([
            'name' => 'required',
            'image' => ['image','mimes:jpeg,png,jpg,gif,svg','max:4096']
        ]);

        if ($request->has('image')) {

            $image = $request->file('image');
            $name = Str::slug($request->input('name')) . '_' . time();
            $folder = '/uploads/images/';
            $filePath = $folder . $name . '.' . $image->getClientOriginalExtension();
            $this->uploadOne($image, $folder, 'public', $name);
        } else {
            $filePath = '';
        }

        $product = new Product([
            Product::COLUMN_NAME => $request->input('name'),
            Product::COLUMN_DESCRIPTION => $request->input('description'),
            Product::COLUMN_IMAGE => $filePath
        ]);

        $product->save();
        return redirect()->route('products.index');
    }

    public function show(Product $product): View
    {
        return view('products.show', compact('product'));
    }

    public function edit(Product $product): View
    {
            return view('products.edit', compact('product'));
    }

    public function update(Request $request, Product $product): RedirectResponse
    {

        $request->validate([
            'name' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        if ($request->has('image')) {
            $image = $request->file('image');
            $name = Str::slug($request->input('name')) . '_' . time();
            $folder = '/uploads/images/';
            $filePath = $folder . $name . '.' . $image->getClientOriginalExtension();
            $this->uploadOne($image, $folder, 'public', $name);
        } else {
            $filePath = '';
        }

        $product->fill([
            Product::COLUMN_NAME => $request->input('name'),
            Product::COLUMN_DESCRIPTION => $request->input('description'),
            Product::COLUMN_IMAGE => $filePath
        ]);
        $product->save();
        return redirect()->route('products.index');
    }

    public function destroy(Product $product): RedirectResponse
    {
        $product->delete();
        return redirect()->route('products.index');
    }
}

resources/views/products/create.blade.php
@extends('App')
@section('title', 'Dodaj produkt')

@section('content')
    <main class="content col-md-9 ms-sm-auto col-lg-10 px-md-4">

    @auth

        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2">@yield('title')</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('products.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-secondary">Powrót do listy</button>
                    </a>
                </div>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="name">Nazwa produktu</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <div class="form-group">
                        <label for="description">Opis produktu</label>
                        <input type="text" class="form-control" id="description" name="description"/>
                    </div>
                    <div class="form-group">
                        <label for="image">Zdjęcie produktu</label>
                        <input type="file" name="image" id="image" class="form-control" placeholder="image" multipart/form-data
                        />
                    </div>
                    <button type="submit" class="btn btn-primary">Zapisz</button>
                </div>
            </div>

        </form>

    @else
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Restricted Area!
        </div>
    @endauth
    </main>
@endsection

resources/views/products/edit.blade.php
@extends('App')
@section('title', 'Edytuj produkt')

@section('content')
    <main class="content col-md-9 ms-sm-auto col-lg-10 px-md-4">
@auth
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2">@yield('title')</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('products.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-secondary">Powrót do listy</button>
                    </a>
                </div>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('products.update', $product->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="nr">Nazwa produktu</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ $product->name }}"/>
                    </div>
                    <div class="form-group">
                        <label for="description">Opis produktu</label>
                        <input type="text" class="form-control" id="description" name="description"
                               value="{{ $product->description }}">
                    </div>
                    <div class="form-group">
                        <label for="image">Zdjęcie produktu</label>
                        <input type="file" name="image" class="form-control" placeholder="image">
                        @if(!empty($product->image))
                            <img src="{{ $product->image }}" width="150px">
                        @endif
                    </div>
                    <button type="submit" class="btn btn-primary">Zapisz</button>
                </div>
            </div>

        </form>

        @else
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Restricted Area!
            </div>
        @endauth
    </main>
    </main>
@endsection

resources/views/products/index.blade.php
@extends('App')
@section('title', 'Lista produktów')

@section('content')
    <div class="content col-md-9 ms-sm-auto col-lg-10 px-md-4">

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2">@yield('title')</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    @auth
                        <a href="{{ URL::to('products/create') }}">
                            <button type="button" class="btn btn-success">Dodaj</button>
                        </a>
                    @endauth

                </div>
            </div>
        </div>
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">

                <form action="{{ route('products.index') }}" method="GET" style="width: 75%">
                    <select class="form-select" aria-label="Wybierz sortowanie" name="sort_by">
                        <option value="" selected>Sortowanie</option>
                        <option value="name">Po nazwie</option>
                        <option value="id">W kolejności utworzenia</option>
                    </select>
                    <select class="form-select" aria-label="Kierunek sortowania" name="sort_order">
                        <option value="" selected>Kierunek</option>
                        <option value="descend">rosnąco</option>
                        <option value="ascend">malejąco</option>
                    </select>
                    <input type="submit" value="Filtruj" class="btn btn-primary h-full mb-1"/>
                </form>
        </div>
        {{ $products->links() }}
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Nazwa</th>
                    <th>Suma cen</th>
                    @auth
                        <th>Akcja</th>@endauth
                </tr>
                </thead>

                <tbody>
                @foreach($products as $product)
                    <tr>
                        <td>{{ $product->id }}</td>
                        <td>
                            <a href="{{ URL::to('products/'.$product->id) }}">{{ $product->name }}</a>
                        </td>
                        <td>
                            {{ count($product->price) }}
                        </td>
                        @auth
                            <td>

                                <a href="{{ route('products.edit', ['product' => $product->id]) }}">
                                    <button type="button" class="btn btn-sm btn-success">Edytuj
                                    </button>
                                </a>
                                <form action="{{ route('products.destroy', ['product' => $product->id]) }}"
                                      method="POST"
                                      style="display: inline;">
                                    @csrf
                                    <input type="hidden" name="_method" value="DELETE"/>
                                    <input type="submit" value="Usuń" name="Usuń" class="btn btn-sm btn-danger"
                                           accesskey="x"/>
                                </form>
                            </td>
                        @endauth
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $products->links() }}
        </div>
        </main>
@endsection

resources/views/products/show.blade.php
@extends('App')
@section('title', 'Zobacz produkt')

@section('content')
    <main class="content col-md-9 ms-sm-auto col-lg-10 px-md-4">

    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <h1 class="h2">@yield('title')</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{ route('products.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Powrót do listy</button>
                </a>&nbsp;
                @auth
                <a href="{{ route('products.edit', ['product' => $product->id]) }}">
                    <button type="button" class="btn btn-sm btn-success">Edytuj
                    </button>
                </a>
                @endauth
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <h4>{{  $product->name }}</h4>
        @if(!empty($product->image))
            <img src="{{ $product->image }}" style="float: left; margin-right:25px; margin-bottom: 50px; max-width:250px;" />
        @endif
        <p>{{  $product->description }}</p>

    <h4 style="margin-top:125px;">Przypisane ceny</h4>
        @foreach($product->price as $price)
            <a href="{{ URL::to('prices/'.$price->id) }}"><span class="badge badge-pill badge-primary">{{ $price->name }}: {{ $price->value }} zł</span></a>
        @endforeach
    </main>
@endsection